name: CI/CD React with Jest

on:
  push:
    branches:
      - dev 
      - release
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Installation des dépendances
      run: npm install

    - name: Exécution des tests Jest
      run: npm run test

    - name: Déploiement sur le VPS
      if: success() && github.ref == 'refs/heads/master'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /srv/www
          git pull origin master
          cd inventory-api
          sudo npm install
          sudo npm run build
          sudo docker compose -f docker-compose.yml up --build -d